name: Lint Check

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  lint:
    name: Run Lint on Node.js Project
    runs-on: ubuntu-latest

    steps:
      # リポジトリのコードを取得（checkout）
      - name: Checkout repository
        uses: actions/checkout@v3

      # Node.jsのセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 依存関係のインストール
      - name: Install dependencies
        run: npm ci

      # lint実行
      - name: Run Lint
        run: npm run lint
